// Generated by design-tokens/generate-colors.py - do not edit manually

import SwiftUI

// MARK: - DesignSystem.Styles.Colors

extension DesignSystem.Styles.Colors {

  // MARK: BackgroundPID_light
  // The backgroundpid_light color. (light)
  static let backgroundPID_lightLight = Color(hex: "#FFFFFF")
  // The backgroundpid_light color. (dark)
  static let backgroundPID_lightDark = Color(hex: "#1D1D1E")

  // MARK: BackgroundPID_medium
  // The backgroundpid_medium color. (light)
  static let backgroundPID_mediumLight = Color(hex: "#F4F4F4")
  // The backgroundpid_medium color. (dark)
  static let backgroundPID_mediumDark = Color(hex: "#49454F")

  // MARK: ColorPID
  // The colorpid color. (light)
  static let colorPIDLight = Color(hex: "#02818B")
  // The colorpid color. (dark)
  static let colorPIDDark = Color(hex: "#A4CCD0")

  // MARK: OnColorPID
  // The oncolorpid color. (light)
  static let onColorPIDLight = Color(hex: "#FFFFFF")
  // The oncolorpid color. (dark)
  static let onColorPIDDark = Color(hex: "#000000")

  // MARK: OnSuccess
  // The onsuccess color. (light)
  static let onSuccessLight = Color(hex: "#0C4A37")
  // The onsuccess color. (dark)
  static let onSuccessDark = Color(hex: "#99D4A2")

  // MARK: Schemes
  // The background color. (light)
  static let schemesBackgroundLight = Color(hex: "#FFFFFF")
  // The background color. (dark)
  static let schemesBackgroundDark = Color(hex: "#141218")

  // The error color. (light)
  static let schemesErrorLight = Color(hex: "#B3261E")
  // The error color. (dark)
  static let schemesErrorDark = Color(hex: "#FFB4AB")

  // The error container color. (light)
  static let schemesErrorContainerLight = Color(hex: "#F9DEDC")
  // The error container color. (dark)
  static let schemesErrorContainerDark = Color(hex: "#8C1D18")

  // The error outline color. (light)
  static let schemesErrorOutlineLight = Color(hex: "#852221")
  // The error outline color. (dark)
  static let schemesErrorOutlineDark = Color(hex: "#F2B8B5")

  // The inverse on surface color. (light)
  static let schemesInverseOnSurfaceLight = Color(hex: "#F5EFF7")
  // The inverse on surface color. (dark)
  static let schemesInverseOnSurfaceDark = Color(hex: "#322F35")

  // The inverse primary color. (light)
  static let schemesInversePrimaryLight = Color(hex: "#D0BCFF")
  // The inverse primary color. (dark)
  static let schemesInversePrimaryDark = Color(hex: "#6750A4")

  // The inverse surface color. (light)
  static let schemesInverseSurfaceLight = Color(hex: "#322F35")
  // The inverse surface color. (dark)
  static let schemesInverseSurfaceDark = Color(hex: "#E6E0E9")

  // The on background color. (light)
  static let schemesOnBackgroundLight = Color(hex: "#1D1D1E")
  // The on background color. (dark)
  static let schemesOnBackgroundDark = Color(hex: "#E6E0E9")

  // The on background variant color. (light)
  static let schemesOnBackgroundVariantLight = Color(hex: "#494949")
  // The on background variant color. (dark)
  static let schemesOnBackgroundVariantDark = Color(hex: "#E6E0E9")

  // The on error color. (light)
  static let schemesOnErrorLight = Color(hex: "#FFFFFF")
  // The on error color. (dark)
  static let schemesOnErrorDark = Color(hex: "#690005")

  // The on error container color. (light)
  static let schemesOnErrorContainerLight = Color(hex: "#852221")
  // The on error container color. (dark)
  static let schemesOnErrorContainerDark = Color(hex: "#F9DEDC")

  // The on primary color. (light)
  static let schemesOnPrimaryLight = Color(hex: "#1D1D1E")
  // The on primary color. (dark)
  static let schemesOnPrimaryDark = Color(hex: "#243600")

  // The on primary container color.
  static let schemesOnPrimaryContainer = Color(hex: "#1D1D1E")

  // The on primary fixed color.
  static let schemesOnPrimaryFixed = Color(hex: "#21005D")

  // The on primary fixed variant color.
  static let schemesOnPrimaryFixedVariant = Color(hex: "#4F378B")

  // The on secondary color. (light)
  static let schemesOnSecondaryLight = Color(hex: "#FFFFFF")
  // The on secondary color. (dark)
  static let schemesOnSecondaryDark = Color(hex: "#302E2C")

  // The on secondary container color. (light)
  static let schemesOnSecondaryContainerLight = Color(hex: "#1D1D1E")
  // The on secondary container color. (dark)
  static let schemesOnSecondaryContainerDark = Color(hex: "#E8DEF8")

  // The on secondary fixed color.
  static let schemesOnSecondaryFixed = Color(hex: "#1D192B")

  // The on secondary fixed variant color.
  static let schemesOnSecondaryFixedVariant = Color(hex: "#4A4458")

  // The on surface color. (light)
  static let schemesOnSurfaceLight = Color(hex: "#1D1D1E")
  // The on surface color. (dark)
  static let schemesOnSurfaceDark = Color(hex: "#E6E0E9")

  // The on surface variant color. (light)
  static let schemesOnSurfaceVariantLight = Color(hex: "#49454F")
  // The on surface variant color. (dark)
  static let schemesOnSurfaceVariantDark = Color(hex: "#CAC4D0")

  // The on tertiary color. (light)
  static let schemesOnTertiaryLight = Color(hex: "#FFFFFF")
  // The on tertiary color. (dark)
  static let schemesOnTertiaryDark = Color(hex: "#1D1D1E")

  // The on tertiary container color. (light)
  static let schemesOnTertiaryContainerLight = Color(hex: "#122118")
  // The on tertiary container color. (dark)
  static let schemesOnTertiaryContainerDark = Color(hex: "#FFD8E4")

  // The on tertiary fixed color.
  static let schemesOnTertiaryFixed = Color(hex: "#31111D")

  // The on tertiary fixed variant color.
  static let schemesOnTertiaryFixedVariant = Color(hex: "#633B48")

  // The outline color. (light)
  static let schemesOutlineLight = Color(hex: "#79747E")
  // The outline color. (dark)
  static let schemesOutlineDark = Color(hex: "#938F99")

  // The outline variant color. (light)
  static let schemesOutlineVariantLight = Color(hex: "#B9B9BD")
  // The outline variant color. (dark)
  static let schemesOutlineVariantDark = Color(hex: "#49454F")

  // The primary color. (light)
  static let schemesPrimaryLight = Color(hex: "#4A6300")
  // The primary color. (dark)
  static let schemesPrimaryDark = Color(hex: "#B5D669")

  // The primary container color.
  static let schemesPrimaryContainer = Color(hex: "#96F5AF")

  // The primary fixed color.
  static let schemesPrimaryFixed = Color(hex: "#EADDFF")

  // The primary fixed dim color.
  static let schemesPrimaryFixedDim = Color(hex: "#D0BCFF")

  // The primary outline color. (light)
  static let schemesPrimaryOutlineLight = Color(hex: "#329D77")
  // The primary outline color. (dark)
  static let schemesPrimaryOutlineDark = Color(hex: "#EADDFF")

  // The scrim color.
  static let schemesScrim = Color(hex: "#000000")

  // The secondary color. (light)
  static let schemesSecondaryLight = Color(hex: "#66605C")
  // The secondary color. (dark)
  static let schemesSecondaryDark = Color(hex: "#C7C7C7")

  // The secondary container color. (light)
  static let schemesSecondaryContainerLight = Color(hex: "#FFFFFF")
  // The secondary container color. (dark)
  static let schemesSecondaryContainerDark = Color(hex: "#4A4458")

  // The secondary fixed color.
  static let schemesSecondaryFixed = Color(hex: "#E8DEF8")

  // The secondary fixed dim color.
  static let schemesSecondaryFixedDim = Color(hex: "#CCC2DC")

  // The shadow color.
  static let schemesShadow = Color(hex: "#000000")

  // The surface color. (light)
  static let schemesSurfaceLight = Color(hex: "#FFFFFF")
  // The surface color. (dark)
  static let schemesSurfaceDark = Color(hex: "#1D1B1E")

  // The surface bright color. (light)
  static let schemesSurfaceBrightLight = Color(hex: "#FEF7FF")
  // The surface bright color. (dark)
  static let schemesSurfaceBrightDark = Color(hex: "#3B383E")

  // The surface container color. (light)
  static let schemesSurfaceContainerLight = Color(hex: "#F4F4F4")
  // The surface container color. (dark)
  static let schemesSurfaceContainerDark = Color(hex: "#211F26")

  // The surface container high color. (light)
  static let schemesSurfaceContainerHighLight = Color(hex: "#ECECF0")
  // The surface container high color. (dark)
  static let schemesSurfaceContainerHighDark = Color(hex: "#2B2930")

  // The surface container highest color. (light)
  static let schemesSurfaceContainerHighestLight = Color(hex: "#DEDEDE")
  // The surface container highest color. (dark)
  static let schemesSurfaceContainerHighestDark = Color(hex: "#36343B")

  // The surface container low color. (light)
  static let schemesSurfaceContainerLowLight = Color(hex: "#F4F4F4")
  // The surface container low color. (dark)
  static let schemesSurfaceContainerLowDark = Color(hex: "#1D1B20")

  // The surface container lowest color. (light)
  static let schemesSurfaceContainerLowestLight = Color(hex: "#FFFFFF")
  // The surface container lowest color. (dark)
  static let schemesSurfaceContainerLowestDark = Color(hex: "#0F0D13")

  // The surface dim color. (light)
  static let schemesSurfaceDimLight = Color(hex: "#DED8E1")
  // The surface dim color. (dark)
  static let schemesSurfaceDimDark = Color(hex: "#141218")

  // The surface tint color. (light)
  static let schemesSurfaceTintLight = Color(hex: "#6750A4")
  // The surface tint color. (dark)
  static let schemesSurfaceTintDark = Color(hex: "#D0BCFF")

  // The surface variant color. (light)
  static let schemesSurfaceVariantLight = Color(hex: "#FFFFFF")
  // The surface variant color. (dark)
  static let schemesSurfaceVariantDark = Color(hex: "#49454F")

  // The tertiary color. (light)
  static let schemesTertiaryLight = Color(hex: "#457D5C")
  // The tertiary color. (dark)
  static let schemesTertiaryDark = Color(hex: "#96F5AF")

  // The tertiary container color. (light)
  static let schemesTertiaryContainerLight = Color(hex: "#EDEDED")
  // The tertiary container color. (dark)
  static let schemesTertiaryContainerDark = Color(hex: "#633B48")

  // The tertiary fixed color.
  static let schemesTertiaryFixed = Color(hex: "#FFD8E4")

  // The tertiary fixed dim color.
  static let schemesTertiaryFixedDim = Color(hex: "#EFB8C8")

  // The tertiary outline color. (light)
  static let schemesTertiaryOutlineLight = Color(hex: "#929294")
  // The tertiary outline color. (dark)
  static let schemesTertiaryOutlineDark = Color(hex: "#FFD8E4")

  // MARK: StateLayers
  // The background opacity-08 color. (light)
  static let stateLayersBackgroundOpacity08Light = Color(hex: "#FEF7FF")
  // The background opacity-08 color. (dark)
  static let stateLayersBackgroundOpacity08Dark = Color(hex: "#141218")

  // The background opacity-12 color. (light)
  static let stateLayersBackgroundOpacity12Light = Color(hex: "#FEF7FF")
  // The background opacity-12 color. (dark)
  static let stateLayersBackgroundOpacity12Dark = Color(hex: "#141218")

  // The background opacity-16 color. (light)
  static let stateLayersBackgroundOpacity16Light = Color(hex: "#FEF7FF")
  // The background opacity-16 color. (dark)
  static let stateLayersBackgroundOpacity16Dark = Color(hex: "#141218")

  // The error opacity-08 color. (light)
  static let stateLayersErrorOpacity08Light = Color(hex: "#B3261E")
  // The error opacity-08 color. (dark)
  static let stateLayersErrorOpacity08Dark = Color(hex: "#F2B8B5")

  // The error opacity-12 color. (light)
  static let stateLayersErrorOpacity12Light = Color(hex: "#B3261E")
  // The error opacity-12 color. (dark)
  static let stateLayersErrorOpacity12Dark = Color(hex: "#F2B8B5")

  // The error opacity-16 color. (light)
  static let stateLayersErrorOpacity16Light = Color(hex: "#B3261E")
  // The error opacity-16 color. (dark)
  static let stateLayersErrorOpacity16Dark = Color(hex: "#F2B8B5")

  // The error container opacity-08 color. (light)
  static let stateLayersErrorContainerOpacity08Light = Color(hex: "#F9DEDC")
  // The error container opacity-08 color. (dark)
  static let stateLayersErrorContainerOpacity08Dark = Color(hex: "#8C1D18")

  // The error container opacity-12 color. (light)
  static let stateLayersErrorContainerOpacity12Light = Color(hex: "#F9DEDC")
  // The error container opacity-12 color. (dark)
  static let stateLayersErrorContainerOpacity12Dark = Color(hex: "#8C1D18")

  // The error container opacity-16 color. (light)
  static let stateLayersErrorContainerOpacity16Light = Color(hex: "#F9DEDC")
  // The error container opacity-16 color. (dark)
  static let stateLayersErrorContainerOpacity16Dark = Color(hex: "#8C1D18")

  // The error outline opacity-08 color. (light)
  static let stateLayersErrorOutlineOpacity08Light = Color(hex: "#F9DEDC")
  // The error outline opacity-08 color. (dark)
  static let stateLayersErrorOutlineOpacity08Dark = Color(hex: "#8C1D18")

  // The error outline opacity-12 color. (light)
  static let stateLayersErrorOutlineOpacity12Light = Color(hex: "#852221")
  // The error outline opacity-12 color. (dark)
  static let stateLayersErrorOutlineOpacity12Dark = Color(hex: "#8C1D18")

  // The error outline opacity-16 color. (light)
  static let stateLayersErrorOutlineOpacity16Light = Color(hex: "#852221")
  // The error outline opacity-16 color. (dark)
  static let stateLayersErrorOutlineOpacity16Dark = Color(hex: "#8C1D18")

  // The inverse on surface opacity-08 color. (light)
  static let stateLayersInverseOnSurfaceOpacity08Light = Color(hex: "#F5EFF7")
  // The inverse on surface opacity-08 color. (dark)
  static let stateLayersInverseOnSurfaceOpacity08Dark = Color(hex: "#322F35")

  // The inverse on surface opacity-12 color. (light)
  static let stateLayersInverseOnSurfaceOpacity12Light = Color(hex: "#F5EFF7")
  // The inverse on surface opacity-12 color. (dark)
  static let stateLayersInverseOnSurfaceOpacity12Dark = Color(hex: "#322F35")

  // The inverse on surface opacity-16 color. (light)
  static let stateLayersInverseOnSurfaceOpacity16Light = Color(hex: "#F5EFF7")
  // The inverse on surface opacity-16 color. (dark)
  static let stateLayersInverseOnSurfaceOpacity16Dark = Color(hex: "#322F35")

  // The inverse primary opacity-08 color. (light)
  static let stateLayersInversePrimaryOpacity08Light = Color(hex: "#D0BCFF")
  // The inverse primary opacity-08 color. (dark)
  static let stateLayersInversePrimaryOpacity08Dark = Color(hex: "#6750A4")

  // The inverse primary opacity-12 color. (light)
  static let stateLayersInversePrimaryOpacity12Light = Color(hex: "#D0BCFF")
  // The inverse primary opacity-12 color. (dark)
  static let stateLayersInversePrimaryOpacity12Dark = Color(hex: "#6750A4")

  // The inverse primary opacity-16 color. (light)
  static let stateLayersInversePrimaryOpacity16Light = Color(hex: "#D0BCFF")
  // The inverse primary opacity-16 color. (dark)
  static let stateLayersInversePrimaryOpacity16Dark = Color(hex: "#6750A4")

  // The inverse surface opacity-08 color. (light)
  static let stateLayersInverseSurfaceOpacity08Light = Color(hex: "#322F35")
  // The inverse surface opacity-08 color. (dark)
  static let stateLayersInverseSurfaceOpacity08Dark = Color(hex: "#E6E0E9")

  // The inverse surface opacity-12 color. (light)
  static let stateLayersInverseSurfaceOpacity12Light = Color(hex: "#322F35")
  // The inverse surface opacity-12 color. (dark)
  static let stateLayersInverseSurfaceOpacity12Dark = Color(hex: "#E6E0E9")

  // The inverse surface opacity-16 color. (light)
  static let stateLayersInverseSurfaceOpacity16Light = Color(hex: "#322F35")
  // The inverse surface opacity-16 color. (dark)
  static let stateLayersInverseSurfaceOpacity16Dark = Color(hex: "#E6E0E9")

  // The on background opacity-08 color. (light)
  static let stateLayersOnBackgroundOpacity08Light = Color(hex: "#1D1B20")
  // The on background opacity-08 color. (dark)
  static let stateLayersOnBackgroundOpacity08Dark = Color(hex: "#E6E0E9")

  // The on background opacity-12 color. (light)
  static let stateLayersOnBackgroundOpacity12Light = Color(hex: "#1D1B20")
  // The on background opacity-12 color. (dark)
  static let stateLayersOnBackgroundOpacity12Dark = Color(hex: "#E6E0E9")

  // The on background opacity-16 color. (light)
  static let stateLayersOnBackgroundOpacity16Light = Color(hex: "#1D1B20")
  // The on background opacity-16 color. (dark)
  static let stateLayersOnBackgroundOpacity16Dark = Color(hex: "#E6E0E9")

  // The on error opacity-08 color. (light)
  static let stateLayersOnErrorOpacity08Light = Color(hex: "#FFFFFF")
  // The on error opacity-08 color. (dark)
  static let stateLayersOnErrorOpacity08Dark = Color(hex: "#601410")

  // The on error opacity-12 color. (light)
  static let stateLayersOnErrorOpacity12Light = Color(hex: "#FFFFFF")
  // The on error opacity-12 color. (dark)
  static let stateLayersOnErrorOpacity12Dark = Color(hex: "#601410")

  // The on error opacity-16 color. (light)
  static let stateLayersOnErrorOpacity16Light = Color(hex: "#FFFFFF")
  // The on error opacity-16 color. (dark)
  static let stateLayersOnErrorOpacity16Dark = Color(hex: "#601410")

  // The on error container opacity-08 color. (light)
  static let stateLayersOnErrorContainerOpacity08Light = Color(hex: "#852221")
  // The on error container opacity-08 color. (dark)
  static let stateLayersOnErrorContainerOpacity08Dark = Color(hex: "#F9DEDC")

  // The on error container opacity-12 color. (light)
  static let stateLayersOnErrorContainerOpacity12Light = Color(hex: "#852221")
  // The on error container opacity-12 color. (dark)
  static let stateLayersOnErrorContainerOpacity12Dark = Color(hex: "#F9DEDC")

  // The on error container opacity-16 color. (light)
  static let stateLayersOnErrorContainerOpacity16Light = Color(hex: "#852221")
  // The on error container opacity-16 color. (dark)
  static let stateLayersOnErrorContainerOpacity16Dark = Color(hex: "#F9DEDC")

  // The on primary opacity-08 color. (light)
  static let stateLayersOnPrimaryOpacity08Light = Color(hex: "#FFFFFF")
  // The on primary opacity-08 color. (dark)
  static let stateLayersOnPrimaryOpacity08Dark = Color(hex: "#381E72")

  // The on primary opacity-12 color. (light)
  static let stateLayersOnPrimaryOpacity12Light = Color(hex: "#FFFFFF")
  // The on primary opacity-12 color. (dark)
  static let stateLayersOnPrimaryOpacity12Dark = Color(hex: "#381E72")

  // The on primary opacity-16 color. (light)
  static let stateLayersOnPrimaryOpacity16Light = Color(hex: "#FFFFFF")
  // The on primary opacity-16 color. (dark)
  static let stateLayersOnPrimaryOpacity16Dark = Color(hex: "#381E72")

  // The on primary container opacity-08 color. (light)
  static let stateLayersOnPrimaryContainerOpacity08Light = Color(hex: "#1D1D1E")
  // The on primary container opacity-08 color. (dark)
  static let stateLayersOnPrimaryContainerOpacity08Dark = Color(hex: "#EADDFF")

  // The on primary container opacity-12 color. (light)
  static let stateLayersOnPrimaryContainerOpacity12Light = Color(hex: "#1D1D1E")
  // The on primary container opacity-12 color. (dark)
  static let stateLayersOnPrimaryContainerOpacity12Dark = Color(hex: "#EADDFF")

  // The on primary container opacity-16 color. (light)
  static let stateLayersOnPrimaryContainerOpacity16Light = Color(hex: "#1D1D1E")
  // The on primary container opacity-16 color. (dark)
  static let stateLayersOnPrimaryContainerOpacity16Dark = Color(hex: "#EADDFF")

  // The on primary fixed opacity-08 color.
  static let stateLayersOnPrimaryFixedOpacity08 = Color(hex: "#21005D")

  // The on primary fixed opacity-12 color.
  static let stateLayersOnPrimaryFixedOpacity12 = Color(hex: "#21005D")

  // The on primary fixed opacity-16 color.
  static let stateLayersOnPrimaryFixedOpacity16 = Color(hex: "#21005D")

  // The on primary fixed variant opacity-08 color.
  static let stateLayersOnPrimaryFixedVariantOpacity08 = Color(hex: "#4F378B")

  // The on primary fixed variant opacity-12 color.
  static let stateLayersOnPrimaryFixedVariantOpacity12 = Color(hex: "#4F378B")

  // The on primary fixed variant opacity-16 color.
  static let stateLayersOnPrimaryFixedVariantOpacity16 = Color(hex: "#4F378B")

  // The on secondary opacity-08 color. (light)
  static let stateLayersOnSecondaryOpacity08Light = Color(hex: "#FFFFFF")
  // The on secondary opacity-08 color. (dark)
  static let stateLayersOnSecondaryOpacity08Dark = Color(hex: "#332D41")

  // The on secondary opacity-12 color. (light)
  static let stateLayersOnSecondaryOpacity12Light = Color(hex: "#FFFFFF")
  // The on secondary opacity-12 color. (dark)
  static let stateLayersOnSecondaryOpacity12Dark = Color(hex: "#332D41")

  // The on secondary opacity-16 color. (light)
  static let stateLayersOnSecondaryOpacity16Light = Color(hex: "#FFFFFF")
  // The on secondary opacity-16 color. (dark)
  static let stateLayersOnSecondaryOpacity16Dark = Color(hex: "#332D41")

  // The on secondary container opacity-08 color. (light)
  static let stateLayersOnSecondaryContainerOpacity08Light = Color(hex: "#4A4459")
  // The on secondary container opacity-08 color. (dark)
  static let stateLayersOnSecondaryContainerOpacity08Dark = Color(hex: "#E8DEF8")

  // The on secondary container opacity-12 color. (light)
  static let stateLayersOnSecondaryContainerOpacity12Light = Color(hex: "#4A4459")
  // The on secondary container opacity-12 color. (dark)
  static let stateLayersOnSecondaryContainerOpacity12Dark = Color(hex: "#E8DEF8")

  // The on secondary container opacity-16 color. (light)
  static let stateLayersOnSecondaryContainerOpacity16Light = Color(hex: "#4A4459")
  // The on secondary container opacity-16 color. (dark)
  static let stateLayersOnSecondaryContainerOpacity16Dark = Color(hex: "#E8DEF8")

  // The on secondary fixed opacity-08 color.
  static let stateLayersOnSecondaryFixedOpacity08 = Color(hex: "#1D192B")

  // The on secondary fixed opacity-12 color.
  static let stateLayersOnSecondaryFixedOpacity12 = Color(hex: "#1D192B")

  // The on secondary fixed opacity-16 color.
  static let stateLayersOnSecondaryFixedOpacity16 = Color(hex: "#1D192B")

  // The on secondary fixed variant opacity-08 color.
  static let stateLayersOnSecondaryFixedVariantOpacity08 = Color(hex: "#4A4458")

  // The on secondary fixed variant opacity-12 color.
  static let stateLayersOnSecondaryFixedVariantOpacity12 = Color(hex: "#4A4458")

  // The on secondary fixed variant opacity-16 color.
  static let stateLayersOnSecondaryFixedVariantOpacity16 = Color(hex: "#4A4458")

  // The on surface opacity-08 color. (light)
  static let stateLayersOnSurfaceOpacity08Light = Color(hex: "#1D1B20")
  // The on surface opacity-08 color. (dark)
  static let stateLayersOnSurfaceOpacity08Dark = Color(hex: "#E6E0E9")

  // The on surface opacity-12 color. (light)
  static let stateLayersOnSurfaceOpacity12Light = Color(hex: "#1D1B20")
  // The on surface opacity-12 color. (dark)
  static let stateLayersOnSurfaceOpacity12Dark = Color(hex: "#E6E0E9")

  // The on surface opacity-16 color. (light)
  static let stateLayersOnSurfaceOpacity16Light = Color(hex: "#1D1B20")
  // The on surface opacity-16 color. (dark)
  static let stateLayersOnSurfaceOpacity16Dark = Color(hex: "#E6E0E9")

  // The on surface variant opacity-08 color. (light)
  static let stateLayersOnSurfaceVariantOpacity08Light = Color(hex: "#49454F")
  // The on surface variant opacity-08 color. (dark)
  static let stateLayersOnSurfaceVariantOpacity08Dark = Color(hex: "#CAC4D0")

  // The on surface variant opacity-12 color. (light)
  static let stateLayersOnSurfaceVariantOpacity12Light = Color(hex: "#49454F")
  // The on surface variant opacity-12 color. (dark)
  static let stateLayersOnSurfaceVariantOpacity12Dark = Color(hex: "#CAC4D0")

  // The on surface variant opacity-16 color. (light)
  static let stateLayersOnSurfaceVariantOpacity16Light = Color(hex: "#49454F")
  // The on surface variant opacity-16 color. (dark)
  static let stateLayersOnSurfaceVariantOpacity16Dark = Color(hex: "#CAC4D0")

  // The on tertiary opacity-08 color. (light)
  static let stateLayersOnTertiaryOpacity08Light = Color(hex: "#FFFFFF")
  // The on tertiary opacity-08 color. (dark)
  static let stateLayersOnTertiaryOpacity08Dark = Color(hex: "#492532")

  // The on tertiary opacity-12 color. (light)
  static let stateLayersOnTertiaryOpacity12Light = Color(hex: "#FFFFFF")
  // The on tertiary opacity-12 color. (dark)
  static let stateLayersOnTertiaryOpacity12Dark = Color(hex: "#492532")

  // The on tertiary opacity-16 color. (light)
  static let stateLayersOnTertiaryOpacity16Light = Color(hex: "#FFFFFF")
  // The on tertiary opacity-16 color. (dark)
  static let stateLayersOnTertiaryOpacity16Dark = Color(hex: "#492532")

  // The on tertiary container opacity-08 color. (light)
  static let stateLayersOnTertiaryContainerOpacity08Light = Color(hex: "#633B48")
  // The on tertiary container opacity-08 color. (dark)
  static let stateLayersOnTertiaryContainerOpacity08Dark = Color(hex: "#FFD8E4")

  // The on tertiary container opacity-12 color. (light)
  static let stateLayersOnTertiaryContainerOpacity12Light = Color(hex: "#633B48")
  // The on tertiary container opacity-12 color. (dark)
  static let stateLayersOnTertiaryContainerOpacity12Dark = Color(hex: "#FFD8E4")

  // The on tertiary container opacity-16 color. (light)
  static let stateLayersOnTertiaryContainerOpacity16Light = Color(hex: "#633B48")
  // The on tertiary container opacity-16 color. (dark)
  static let stateLayersOnTertiaryContainerOpacity16Dark = Color(hex: "#FFD8E4")

  // The on tertiary fixed opacity-08 color.
  static let stateLayersOnTertiaryFixedOpacity08 = Color(hex: "#31111D")

  // The on tertiary fixed opacity-12 color.
  static let stateLayersOnTertiaryFixedOpacity12 = Color(hex: "#31111D")

  // The on tertiary fixed opacity-16 color.
  static let stateLayersOnTertiaryFixedOpacity16 = Color(hex: "#31111D")

  // The on tertiary fixed variant opacity-08 color.
  static let stateLayersOnTertiaryFixedVariantOpacity08 = Color(hex: "#633B48")

  // The on tertiary fixed variant opacity-12 color.
  static let stateLayersOnTertiaryFixedVariantOpacity12 = Color(hex: "#633B48")

  // The on tertiary fixed variant opacity-16 color.
  static let stateLayersOnTertiaryFixedVariantOpacity16 = Color(hex: "#633B48")

  // The outline opacity-08 color. (light)
  static let stateLayersOutlineOpacity08Light = Color(hex: "#79747E")
  // The outline opacity-08 color. (dark)
  static let stateLayersOutlineOpacity08Dark = Color(hex: "#938F99")

  // The outline opacity-12 color. (light)
  static let stateLayersOutlineOpacity12Light = Color(hex: "#79747E")
  // The outline opacity-12 color. (dark)
  static let stateLayersOutlineOpacity12Dark = Color(hex: "#938F99")

  // The outline opacity-16 color. (light)
  static let stateLayersOutlineOpacity16Light = Color(hex: "#79747E")
  // The outline opacity-16 color. (dark)
  static let stateLayersOutlineOpacity16Dark = Color(hex: "#938F99")

  // The outline variant opacity-08 color. (light)
  static let stateLayersOutlineVariantOpacity08Light = Color(hex: "#CAC4D0")
  // The outline variant opacity-08 color. (dark)
  static let stateLayersOutlineVariantOpacity08Dark = Color(hex: "#49454F")

  // The outline variant opacity-12 color. (light)
  static let stateLayersOutlineVariantOpacity12Light = Color(hex: "#CAC4D0")
  // The outline variant opacity-12 color. (dark)
  static let stateLayersOutlineVariantOpacity12Dark = Color(hex: "#49454F")

  // The outline variant opacity-16 color. (light)
  static let stateLayersOutlineVariantOpacity16Light = Color(hex: "#CAC4D0")
  // The outline variant opacity-16 color. (dark)
  static let stateLayersOutlineVariantOpacity16Dark = Color(hex: "#49454F")

  // The primary opacity-08 color. (light)
  static let stateLayersPrimaryOpacity08Light = Color(hex: "#96F5AF")
  // The primary opacity-08 color. (dark)
  static let stateLayersPrimaryOpacity08Dark = Color(hex: "#D0BCFE")

  // The primary opacity-12 color. (light)
  static let stateLayersPrimaryOpacity12Light = Color(hex: "#96F5AF")
  // The primary opacity-12 color. (dark)
  static let stateLayersPrimaryOpacity12Dark = Color(hex: "#D0BCFE")

  // The primary opacity-16 color. (light)
  static let stateLayersPrimaryOpacity16Light = Color(hex: "#96F5AF")
  // The primary opacity-16 color. (dark)
  static let stateLayersPrimaryOpacity16Dark = Color(hex: "#D0BCFE")

  // The primary container opacity-08 color. (light)
  static let stateLayersPrimaryContainerOpacity08Light = Color(hex: "#96F5AF")
  // The primary container opacity-08 color. (dark)
  static let stateLayersPrimaryContainerOpacity08Dark = Color(hex: "#4F378B")

  // The primary container opacity-12 color. (light)
  static let stateLayersPrimaryContainerOpacity12Light = Color(hex: "#96F5AF")
  // The primary container opacity-12 color. (dark)
  static let stateLayersPrimaryContainerOpacity12Dark = Color(hex: "#4F378B")

  // The primary container opacity-16 color. (light)
  static let stateLayersPrimaryContainerOpacity16Light = Color(hex: "#96F5AF")
  // The primary container opacity-16 color. (dark)
  static let stateLayersPrimaryContainerOpacity16Dark = Color(hex: "#4F378B")

  // The primary fixed opacity-08 color.
  static let stateLayersPrimaryFixedOpacity08 = Color(hex: "#EADDFF")

  // The primary fixed opacity-12 color.
  static let stateLayersPrimaryFixedOpacity12 = Color(hex: "#EADDFF")

  // The primary fixed opacity-16 color.
  static let stateLayersPrimaryFixedOpacity16 = Color(hex: "#EADDFF")

  // The primary fixed dim opacity-08 color.
  static let stateLayersPrimaryFixedDimOpacity08 = Color(hex: "#D0BCFF")

  // The primary fixed dim opacity-12 color.
  static let stateLayersPrimaryFixedDimOpacity12 = Color(hex: "#D0BCFF")

  // The primary fixed dim opacity-16 color.
  static let stateLayersPrimaryFixedDimOpacity16 = Color(hex: "#D0BCFF")

  // The primary outline opacity-08 color. (light)
  static let stateLayersPrimaryOutlineOpacity08Light = Color(hex: "#EADDFF")
  // The primary outline opacity-08 color. (dark)
  static let stateLayersPrimaryOutlineOpacity08Dark = Color(hex: "#4F378B")

  // The primary outline opacity-12 color. (light)
  static let stateLayersPrimaryOutlineOpacity12Light = Color(hex: "#EADDFF")
  // The primary outline opacity-12 color. (dark)
  static let stateLayersPrimaryOutlineOpacity12Dark = Color(hex: "#4F378B")

  // The primary outline opacity-16 color. (light)
  static let stateLayersPrimaryOutlineOpacity16Light = Color(hex: "#329D77")
  // The primary outline opacity-16 color. (dark)
  static let stateLayersPrimaryOutlineOpacity16Dark = Color(hex: "#4F378B")

  // The scrim opacity-08 color.
  static let stateLayersScrimOpacity08 = Color(hex: "#000000")

  // The scrim opacity-12 color.
  static let stateLayersScrimOpacity12 = Color(hex: "#000000")

  // The scrim opacity-16 color.
  static let stateLayersScrimOpacity16 = Color(hex: "#000000")

  // The secondary opacity-08 color. (light)
  static let stateLayersSecondaryOpacity08Light = Color(hex: "#625B71")
  // The secondary opacity-08 color. (dark)
  static let stateLayersSecondaryOpacity08Dark = Color(hex: "#CCC2DC")

  // The secondary opacity-12 color. (light)
  static let stateLayersSecondaryOpacity12Light = Color(hex: "#625B71")
  // The secondary opacity-12 color. (dark)
  static let stateLayersSecondaryOpacity12Dark = Color(hex: "#CCC2DC")

  // The secondary opacity-16 color. (light)
  static let stateLayersSecondaryOpacity16Light = Color(hex: "#625B71")
  // The secondary opacity-16 color. (dark)
  static let stateLayersSecondaryOpacity16Dark = Color(hex: "#CCC2DC")

  // The secondary container opacity-08 color. (light)
  static let stateLayersSecondaryContainerOpacity08Light = Color(hex: "#E8DEF8")
  // The secondary container opacity-08 color. (dark)
  static let stateLayersSecondaryContainerOpacity08Dark = Color(hex: "#4A4458")

  // The secondary container opacity-12 color. (light)
  static let stateLayersSecondaryContainerOpacity12Light = Color(hex: "#E8DEF8")
  // The secondary container opacity-12 color. (dark)
  static let stateLayersSecondaryContainerOpacity12Dark = Color(hex: "#4A4458")

  // The secondary container opacity-16 color. (light)
  static let stateLayersSecondaryContainerOpacity16Light = Color(hex: "#E8DEF8")
  // The secondary container opacity-16 color. (dark)
  static let stateLayersSecondaryContainerOpacity16Dark = Color(hex: "#4A4458")

  // The secondary fixed opacity-08 color.
  static let stateLayersSecondaryFixedOpacity08 = Color(hex: "#E8DEF8")

  // The secondary fixed opacity-12 color.
  static let stateLayersSecondaryFixedOpacity12 = Color(hex: "#E8DEF8")

  // The secondary fixed opacity-16 color.
  static let stateLayersSecondaryFixedOpacity16 = Color(hex: "#E8DEF8")

  // The secondary fixed dim opacity-08 color.
  static let stateLayersSecondaryFixedDimOpacity08 = Color(hex: "#CCC2DC")

  // The secondary fixed dim opacity-12 color.
  static let stateLayersSecondaryFixedDimOpacity12 = Color(hex: "#CCC2DC")

  // The secondary fixed dim opacity-16 color.
  static let stateLayersSecondaryFixedDimOpacity16 = Color(hex: "#CCC2DC")

  // The shadow opacity-08 color.
  static let stateLayersShadowOpacity08 = Color(hex: "#000000")

  // The shadow opacity-12 color.
  static let stateLayersShadowOpacity12 = Color(hex: "#000000")

  // The shadow opacity-16 color.
  static let stateLayersShadowOpacity16 = Color(hex: "#000000")

  // The surface opacity-08 color. (light)
  static let stateLayersSurfaceOpacity08Light = Color(hex: "#FEF7FF")
  // The surface opacity-08 color. (dark)
  static let stateLayersSurfaceOpacity08Dark = Color(hex: "#141218")

  // The surface opacity-12 color. (light)
  static let stateLayersSurfaceOpacity12Light = Color(hex: "#FEF7FF")
  // The surface opacity-12 color. (dark)
  static let stateLayersSurfaceOpacity12Dark = Color(hex: "#141218")

  // The surface opacity-16 color. (light)
  static let stateLayersSurfaceOpacity16Light = Color(hex: "#FEF7FF")
  // The surface opacity-16 color. (dark)
  static let stateLayersSurfaceOpacity16Dark = Color(hex: "#141218")

  // The surface bright opacity-08 color. (light)
  static let stateLayersSurfaceBrightOpacity08Light = Color(hex: "#FEF7FF")
  // The surface bright opacity-08 color. (dark)
  static let stateLayersSurfaceBrightOpacity08Dark = Color(hex: "#3B383E")

  // The surface bright opacity-12 color. (light)
  static let stateLayersSurfaceBrightOpacity12Light = Color(hex: "#FEF7FF")
  // The surface bright opacity-12 color. (dark)
  static let stateLayersSurfaceBrightOpacity12Dark = Color(hex: "#3B383E")

  // The surface bright opacity-16 color. (light)
  static let stateLayersSurfaceBrightOpacity16Light = Color(hex: "#FEF7FF")
  // The surface bright opacity-16 color. (dark)
  static let stateLayersSurfaceBrightOpacity16Dark = Color(hex: "#3B383E")

  // The surface container opacity-08 color. (light)
  static let stateLayersSurfaceContainerOpacity08Light = Color(hex: "#F3EDF7")
  // The surface container opacity-08 color. (dark)
  static let stateLayersSurfaceContainerOpacity08Dark = Color(hex: "#211F26")

  // The surface container opacity-12 color. (light)
  static let stateLayersSurfaceContainerOpacity12Light = Color(hex: "#F3EDF7")
  // The surface container opacity-12 color. (dark)
  static let stateLayersSurfaceContainerOpacity12Dark = Color(hex: "#211F26")

  // The surface container opacity-16 color. (light)
  static let stateLayersSurfaceContainerOpacity16Light = Color(hex: "#F3EDF7")
  // The surface container opacity-16 color. (dark)
  static let stateLayersSurfaceContainerOpacity16Dark = Color(hex: "#211F26")

  // The surface container high opacity-08 color. (light)
  static let stateLayersSurfaceContainerHighOpacity08Light = Color(hex: "#ECE6F0")
  // The surface container high opacity-08 color. (dark)
  static let stateLayersSurfaceContainerHighOpacity08Dark = Color(hex: "#2B2930")

  // The surface container high opacity-12 color. (light)
  static let stateLayersSurfaceContainerHighOpacity12Light = Color(hex: "#ECE6F0")
  // The surface container high opacity-12 color. (dark)
  static let stateLayersSurfaceContainerHighOpacity12Dark = Color(hex: "#2B2930")

  // The surface container high opacity-16 color. (light)
  static let stateLayersSurfaceContainerHighOpacity16Light = Color(hex: "#ECE6F0")
  // The surface container high opacity-16 color. (dark)
  static let stateLayersSurfaceContainerHighOpacity16Dark = Color(hex: "#2B2930")

  // The surface container highest opacity-08 color. (light)
  static let stateLayersSurfaceContainerHighestOpacity08Light = Color(hex: "#E6E0E9")
  // The surface container highest opacity-08 color. (dark)
  static let stateLayersSurfaceContainerHighestOpacity08Dark = Color(hex: "#36343B")

  // The surface container highest opacity-12 color. (light)
  static let stateLayersSurfaceContainerHighestOpacity12Light = Color(hex: "#E6E0E9")
  // The surface container highest opacity-12 color. (dark)
  static let stateLayersSurfaceContainerHighestOpacity12Dark = Color(hex: "#36343B")

  // The surface container highest opacity-16 color. (light)
  static let stateLayersSurfaceContainerHighestOpacity16Light = Color(hex: "#E6E0E9")
  // The surface container highest opacity-16 color. (dark)
  static let stateLayersSurfaceContainerHighestOpacity16Dark = Color(hex: "#36343B")

  // The surface container low opacity-08 color. (light)
  static let stateLayersSurfaceContainerLowOpacity08Light = Color(hex: "#F7F2FA")
  // The surface container low opacity-08 color. (dark)
  static let stateLayersSurfaceContainerLowOpacity08Dark = Color(hex: "#1D1B20")

  // The surface container low opacity-12 color. (light)
  static let stateLayersSurfaceContainerLowOpacity12Light = Color(hex: "#F7F2FA")
  // The surface container low opacity-12 color. (dark)
  static let stateLayersSurfaceContainerLowOpacity12Dark = Color(hex: "#1D1B20")

  // The surface container low opacity-16 color. (light)
  static let stateLayersSurfaceContainerLowOpacity16Light = Color(hex: "#F7F2FA")
  // The surface container low opacity-16 color. (dark)
  static let stateLayersSurfaceContainerLowOpacity16Dark = Color(hex: "#1D1B20")

  // The surface container lowest opacity-08 color. (light)
  static let stateLayersSurfaceContainerLowestOpacity08Light = Color(hex: "#FFFFFF")
  // The surface container lowest opacity-08 color. (dark)
  static let stateLayersSurfaceContainerLowestOpacity08Dark = Color(hex: "#0F0D13")

  // The surface container lowest opacity-12 color. (light)
  static let stateLayersSurfaceContainerLowestOpacity12Light = Color(hex: "#FFFFFF")
  // The surface container lowest opacity-12 color. (dark)
  static let stateLayersSurfaceContainerLowestOpacity12Dark = Color(hex: "#0F0D13")

  // The surface container lowest opacity-16 color. (light)
  static let stateLayersSurfaceContainerLowestOpacity16Light = Color(hex: "#FFFFFF")
  // The surface container lowest opacity-16 color. (dark)
  static let stateLayersSurfaceContainerLowestOpacity16Dark = Color(hex: "#0F0D13")

  // The surface dim opacity-08 color. (light)
  static let stateLayersSurfaceDimOpacity08Light = Color(hex: "#DED8E1")
  // The surface dim opacity-08 color. (dark)
  static let stateLayersSurfaceDimOpacity08Dark = Color(hex: "#141218")

  // The surface dim opacity-12 color. (light)
  static let stateLayersSurfaceDimOpacity12Light = Color(hex: "#DED8E1")
  // The surface dim opacity-12 color. (dark)
  static let stateLayersSurfaceDimOpacity12Dark = Color(hex: "#141218")

  // The surface dim opacity-16 color. (light)
  static let stateLayersSurfaceDimOpacity16Light = Color(hex: "#DED8E1")
  // The surface dim opacity-16 color. (dark)
  static let stateLayersSurfaceDimOpacity16Dark = Color(hex: "#141218")

  // The surface tint opacity-08 color. (light)
  static let stateLayersSurfaceTintOpacity08Light = Color(hex: "#6750A4")
  // The surface tint opacity-08 color. (dark)
  static let stateLayersSurfaceTintOpacity08Dark = Color(hex: "#D0BCFF")

  // The surface tint opacity-12 color. (light)
  static let stateLayersSurfaceTintOpacity12Light = Color(hex: "#6750A4")
  // The surface tint opacity-12 color. (dark)
  static let stateLayersSurfaceTintOpacity12Dark = Color(hex: "#D0BCFF")

  // The surface tint opacity-16 color. (light)
  static let stateLayersSurfaceTintOpacity16Light = Color(hex: "#6750A4")
  // The surface tint opacity-16 color. (dark)
  static let stateLayersSurfaceTintOpacity16Dark = Color(hex: "#D0BCFF")

  // The surface variant opacity-08 color. (light)
  static let stateLayersSurfaceVariantOpacity08Light = Color(hex: "#E7E0EC")
  // The surface variant opacity-08 color. (dark)
  static let stateLayersSurfaceVariantOpacity08Dark = Color(hex: "#49454F")

  // The surface variant opacity-12 color. (light)
  static let stateLayersSurfaceVariantOpacity12Light = Color(hex: "#E7E0EC")
  // The surface variant opacity-12 color. (dark)
  static let stateLayersSurfaceVariantOpacity12Dark = Color(hex: "#49454F")

  // The surface variant opacity-16 color. (light)
  static let stateLayersSurfaceVariantOpacity16Light = Color(hex: "#E7E0EC")
  // The surface variant opacity-16 color. (dark)
  static let stateLayersSurfaceVariantOpacity16Dark = Color(hex: "#49454F")

  // The tertiary opacity-08 color. (light)
  static let stateLayersTertiaryOpacity08Light = Color(hex: "#7D5260")
  // The tertiary opacity-08 color. (dark)
  static let stateLayersTertiaryOpacity08Dark = Color(hex: "#EFB8C8")

  // The tertiary opacity-12 color. (light)
  static let stateLayersTertiaryOpacity12Light = Color(hex: "#7D5260")
  // The tertiary opacity-12 color. (dark)
  static let stateLayersTertiaryOpacity12Dark = Color(hex: "#EFB8C8")

  // The tertiary opacity-16 color. (light)
  static let stateLayersTertiaryOpacity16Light = Color(hex: "#7D5260")
  // The tertiary opacity-16 color. (dark)
  static let stateLayersTertiaryOpacity16Dark = Color(hex: "#EFB8C8")

  // The tertiary container opacity-08 color. (light)
  static let stateLayersTertiaryContainerOpacity08Light = Color(hex: "#FFD8E4")
  // The tertiary container opacity-08 color. (dark)
  static let stateLayersTertiaryContainerOpacity08Dark = Color(hex: "#633B48")

  // The tertiary container opacity-12 color. (light)
  static let stateLayersTertiaryContainerOpacity12Light = Color(hex: "#FFD8E4")
  // The tertiary container opacity-12 color. (dark)
  static let stateLayersTertiaryContainerOpacity12Dark = Color(hex: "#633B48")

  // The tertiary container opacity-16 color. (light)
  static let stateLayersTertiaryContainerOpacity16Light = Color(hex: "#FFD8E4")
  // The tertiary container opacity-16 color. (dark)
  static let stateLayersTertiaryContainerOpacity16Dark = Color(hex: "#633B48")

  // The tertiary fixed opacity-08 color.
  static let stateLayersTertiaryFixedOpacity08 = Color(hex: "#FFD8E4")

  // The tertiary fixed opacity-12 color.
  static let stateLayersTertiaryFixedOpacity12 = Color(hex: "#FFD8E4")

  // The tertiary fixed opacity-16 color.
  static let stateLayersTertiaryFixedOpacity16 = Color(hex: "#FFD8E4")

  // The tertiary fixed dim opacity-08 color.
  static let stateLayersTertiaryFixedDimOpacity08 = Color(hex: "#EFB8C8")

  // The tertiary fixed dim opacity-12 color.
  static let stateLayersTertiaryFixedDimOpacity12 = Color(hex: "#EFB8C8")

  // The tertiary fixed dim opacity-16 color.
  static let stateLayersTertiaryFixedDimOpacity16 = Color(hex: "#EFB8C8")

  // MARK: Success
  // The success color. (light)
  static let successLight = Color(hex: "#C2FFC4")
  // The success color. (dark)
  static let successDark = Color(hex: "#243600")

  // MARK: Warning
  // The warning color. (light)
  static let warningLight = Color(hex: "#FF9900")
  // The warning color. (dark)
  static let warningDark = Color(hex: "#FFC774")
}
