/*
 * Copyright (c) 2023 European Commission
 *
 * Licensed under the EUPL, Version 1.2 or - as soon they will be approved by the European
 * Commission - subsequent versions of the EUPL (the "Licence"); You may not use this work
 * except in compliance with the Licence.
 *
 * You may obtain a copy of the Licence at:
 * https://joinup.ec.europa.eu/software/page/eupl
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the Licence is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF
 * ANY KIND, either express or implied. See the Licence for the specific language
 * governing permissions and limitations under the Licence.
 */
import SwiftUI

public enum LocalizableStringKey: Equatable, Sendable {
  case dynamic(key: String)
  case custom(String)
  case space
  case search
  case genericErrorTitle
  case genericErrorDesc
  case biometryOpenSettings
  case biometryConfirmRequest
  case invalidQuickPin
  case tryAgain
  case shareButton
  case cancelButton
  case requestDataCaption
  case requestDataInfoNotice
  case requestDataTitle([String])
  case documentAdded
  case requestDataSheetCaption
  case okButton
  case shareDataReview
  case success
  case successfullySharedFollowingInformation
  case incompleteRequestDataSelection
  case addDoc
  case filters
  case sortByIssuedDateSectionTitle
  case issuerSectionTitle
  case showResults
  case showQRTap
  case welcomeBack([String])
  case viewDocumentDetails
  case pleaseWait
  case requestDataShareQuickPinCaption
  case requestDataShareBiometryCaption
  case addDocumentTitle
  case addDocumentSubtitle
  case addDocumentRequest
  case proximityConnectivityCaption
  case unavailableField
  case requestDataVerifiedEntity
  case requestDataVerifiedEntityMessage
  case moreOptions
  case changeQuickPinOption
  case quickPinSetTitle
  case quickPinEnterPin
  case quickPinConfirmPin
  case quickPinSetCaptionOne
  case quickPinSetCaptionTwo
  case quickPinNextButton
  case quickPinConfirmButton
  case quickPinSetSuccess
  case loginTitle
  case loginCaptionQuickPinOnly
  case loginCaption
  case quickPinSetSuccessButton
  case quickPinDoNotMatch
  case quickPinUpdateTitle
  case quickPinUpdateCaptionOne
  case quickPinUpdateCaptionTwo
  case quickPinUpdateCaptionThree
  case quickPinUpdateSuccess
  case quickPinUpdateSuccessButton
  case quickPinUpdateCancellationTitle
  case quickPinUpdateCancellationCaption
  case quickPinUpdateCancellationContinue
  case issuanceDetailsContinueButton
  case successTitlePunctuated
  case issuanceSuccessCaption([String])
  case issuanceSuccessNextButton
  case issuerWantWalletAddition
  case unknownVerifier
  case unknownIssuer
  case genericIssuer
  case filterByIssuer
  case yes
  case no
  case scanQrCode
  case signDocument
  case signDocumentSubtitle
  case selectDocument
  case validUntil([String])
  case bleDisabledModalTitle
  case bleDisabledModalCaption
  case bleDisabledModalButton
  case requestDataNoDocument
  case issuanceDetailsDeletionTitle([String])
  case deleteDocument
  case issuanceDetailsDeletionCaption([String])
  case errorUnableFetchDocuments
  case errorUnableFetchDocument
  case scannerQrTitleIssuing
  case scannerQrTitlePresentation
  case scannerQrCaptionIssuing
  case scannerQrCaptionPresentation
  case scannerQrTitle
  case scannerQrCaption
  case cameraError
  case missingPid
  case requestCredentialOfferTitle([String])
  case requestCredentialOfferCaption
  case requestCredentialOfferNoDocument
  case unableToIssueAndStore
  case missingMetadata
  case issueButton
  case cancelIssueSheetTitle
  case cancelIssueSheetCaption
  case cancelIssueSheetContinue
  case credentialOfferSuccessButton
  case credentialOfferSuccessCaption([String])
  case credentialOfferPartialSuccessCaption([String])
  case issuanceCodeTitle([String])
  case issuanceCodeCaption([String])
  case transactionCodeFormatError([String])
  case inProgress
  case scopedIssuanceSuccessDeferredCaption
  case scopedIssuanceSuccessDeferredCaptionDocName([String])
  case scopedIssuanceSuccessDeferredCaptionDocNameAndIssuer([String])
  case issuanceSuccessDeferredCaption([String])
  case pending
  case issuanceFailed
  case deferredDocumentsIssuedModalTitle
  case defferedDocumentsIssuedModalCaption
  case retrieveLogs
  case qrScanInformativeText
  case unableToPresentAndShare
  case itemNotFoundInStorage
  case itemsNotFoundInStorage
  case home
  case documents
  case transactions
  case authenticateAuthoriseTransactions
  case electronicallySignDigitalDocuments
  case learnMore
  case chooseFromList
  case chooseFromListTitle
  case addDocumentsToWallet
  case details
  case dataSharingRequest
  case dataShared
  case doneButton
  case dataSharingTitle
  case close
  case reset
  case all
  case descending
  case ascending
  case issuanceSuccessHeaderDescriptionWhenError
  case trustedRelyingParty
  case trustedRelyingPartyDescription
  case alertAccessOnlineServices
  case alertAccessOnlineServicesMessage
  case alertSignDocumentsSafely
  case alertSignDocumentsSafelyMessage
  case authenticate
  case inPerson
  case online
  case fromDevice
  case autodashboardAuthenticateDialogMessage
  case deleteButton
  case savedToFavorites
  case succesfullyAddedFollowingToWallet
  case removedFromFavorites
  case savedToFavoritesMessage
  case removedFromFavoritesMessages
  case viewDetails([String])
  case requestsTheFollowing
  case walletIsSecured
  case noResults
  case noResultsDescription
  case proximityConnectionNfcDescription
  case orShareViaNfc
  case expiryPeriodSectionTitle
  case selectExpiryPeriod
  case filterByState
  case sortBy
  case deleteDocumentConfirmDialog
  case defaultLabel
  case valid
  case revoke
  case expired
  case dateIssued
  case expiryDate
  case nextSevenDays
  case nextThirtyDays
  case beyondThiryDays
  case beforeToday
  case issuanceRequest
  case myEuWallet
  case categoryGovernment
  case categoryHealth
  case categoryEducation
  case categoryFinance
  case categoryRetail
  case categoryOther
  case categorySocialSecurity
  case categoryTravel
  case changelog
  case orderBy
  case filterByCategory
  case searchDocuments
  case pidPresentationMalformedPresentationTitle
  case pidPresentationMalformedPresentationParagraph
  case pidPresentationMalformedPresentationPrimButton
  case pidPresentationCredentialNotFoundTitle
  case pidPresentationCredentialNotFoundParagraph
  case pidPresentationCredentialNotFoundPrimButton
  case presentationConfirmationTitle([String])
  case presentationConfirmationDescription1([String])
  case presentationConfirmationDescription2([String])
  case presentationConfirmationContinueButton
  case presentationConfirmationCancelButton
  case rpConsentTitle
  case sendData
  case passwordEntryTitle
  case enterPassword
  case whatIsPassword
  case dataSentSuccessfully
  case dataSentSuccessfullyMessage
  case backToProvider
  case reportProblem
  case whatIsSecurityPassword
  case whatIsSecurityPasswordMessage
  case enterSecurityPassword
  case enterYourPassword
  case purpose
  case accountOpening
  case requiredData
  case onlyFollowingdataWillBeSent
  case personalData
  case reject
  case returnUser
  case yesReject
  case confirmItendificationRefusal
  case confirmItendificationRefusalMessage
  case certificate
  case signature
  case issuer
  case country
  case rpDetails
  case publisher
  case distributor
  case activity
  case validInUntil
  case createdOn
  case deletePID([String])
  case createWithPersonalAusweis([String])
  case name
  case firstName
  case givenName
  case lastName
  case familyName
  case title
  case nationality
  case dateOfBirth
  case placeOfBirth
  case issuingCountry
  case issuingAuthority
  case address
  case birthYear
  case ageInYears
  case birthFamilyName
  case ageEqualOrOver
  case issuingDate
  case dashboardCardTitle
  case years
  case errorFetchTransactionLog
  case parSetupFailed
  case createdDate
  case next
  case back
  case showDetails
  case hideDetails
  case consentViewHeader(Int, Int, String)
  case whyIsThisDataNeededTitle
  case whyIsThisDataNeededDescription
  case appName
  case cardPinEnteredWrongTwice
  case canInfoTitle
  case canInfoDesc
  case canEingeben
  case issuanceCanEntryTitle
  case issuanceErrorWrongCan
  case cardPinEnteredWrongDescription
  case securityCheckAlertTile
  case securityCheckAlertDescription
  case securityCheckButtonTitle
  case issuanceEidPinEntryTitle
  case issuanceScanningTitle
  case issuanceButtonKartenPin
  case issuanceButtonFindBurgeramt
  case issuanceEidUnkownParagraph1
  case issuanceEidUnkownParagraph2
  case issuanceEidUnkownParagraph31
  case issuanceEidUnkownParagraph32
  case issuanceEidUnkownParagraph33
  case issuanceEidUnkownTitle
  case setupPinTitle
  case setupPinPrimaryButtonTitle
  case setupPinSecondaryButtonTitle
  case setupPinMessage
  case setupPinTransportViewTitle
  case setupPinTransportViewPrimaryButtonTitle
  case setupPinTransportViewSecondaryButtonTitle
  case setupPinTransportViewMessage
  case setupPinSheetTitle
  case setupPinSheetMessage
  case setupPinSheetButtonText
  case transportPinViewTitle
  case setupNewPinInstructionViewTitle
  case eidSetupCardPinIntroParagraph
  case setupNewPinInstructionViewPrimaryButtonTilte
  case setupNewPinInstructionViewSecondaryButtonTitle
  case confirmationPinMismatch
  case scanningTips
  case scanningGuidePara1
  case scanningGuidePara2
  case scanningGuidePara3
  case scanningBannerIOS
  case restartScanning
  case scanningHelpPopupTitle
  case scanningHelpPopupDetailPara1
  case scanningHelpPopupDetailPara2
  case scanningHelpPopupDetailPara3
  case scanningHelpCustomerServiceCalling
  case scanningCustomerServicePhoneNumber
  case transportPinCorrect
  case cardPinSet
  case setNewEidPinOne
  case setNewEidPinTwo
  case tryAgainIn
  case walletPinForgotten
  case walletPinMultipleWrongEntry
  case issuanceOnboardingTitle
  case issuanceOnboardingMessage
  case issuanceOnboardingPinInfoViewTitle
  case issuanceOnboardingPinInfoViewMessage
  case issuanceOnboardingPinInfoViewPrimaryButtonTitle
  case issuanceOnboardingPinInfoViewSecondaryButtonTitle
  case issuanceOnboardingPinInfoViewTertiaryButtonTitle
  case issuanceOnboardingPinInfoViewHelpButtonTitle
  case pidNoCardAvailableInfoTitle
  case pidNoCardAvailableInfoParagraph
  case globalOfficeButton
  case issuanceOnboardingPrimaryButtonTitle
  case pidOnboardingCardsTitle
  case pidOnboardingCardsList1
  case pidOnboardingCardsList2
  case pidOnboardingCardsPrimButton
  case pidOnboardingCardsSecButton
  case pidOnboardingCardsTertButton
  case pidProcessOverviewTitle
  case pidProcessOverviewList1
  case pidProcessOverviewList2
  case pidProcessOverviewList3
  case pidProcessOverviewList4
  case pidProcessOverviewTertButton
  case pidProcessOverviewPrimButton
  case pidIDPreviewTitle
  case pidIDPreviewIssuerLabel
  case pidIDPreviewCredentialSubline
  case pidIDPreviewIssuerName
  case walletPinSetupBanner
  case pidEidFunctionInfoTitle
  case pidEidFunctionInfoParagraph1
  case pidEidFunctionInfoParagraph2
  case globalCloseHintButton
  case globalCloseButton
  case kartenPinCorrect
  case walletPinSetupTitle
  case walletPinSetupWarning
  case walletPinSetupPrimaryButtonTitle
  case setWalletPinTitle
  case continueTitle
  case walletPinSetupConfirmTitle
  case setupWalletPinIncorrectRetypeEntry
  case tryAgainInFewMinutes
  case serverUnavailable
  case walletPinTryAgainIn
  case walletPinLastTryLeft
  case walletPinBlockedMessage
  case walletPinRetryInfoDetail
  case walletPinWrongEntry
  case walletPinForgotPopupDesc
  case walletResetNow
  case deleteEidConfirmationTitle
  case deleteEidConfirmationMessage
  case digitalIdDeleted
  case toWallet
  case dashboardScreenSecondaryText
  case dashboardPrimaryButtonTitle
  case issuanceConsentViewTitle
  case issuanceDigitalID
  case issuanceConsentViewPrimaryButtonTitle
  case issuanceConsentViewSecondaryButtonTitle
  case issuanceConsentViewShowMoreDataButtonTitle
  case issuanceConsentViewShowLessDataButtonTitle
  case issuanceConsentRejectInfoTitle
  case issuanceConsentRejectInfoParagraph
  case issuanceConsentRejectInfoPrimaryButtonTitle
  case email
  case privacyPolicy
  case certificateValidUntil
  case issuedBy
  case canCorrect
  case canCorrectDescription
  case canCorrectPrimButton
  case canCorrectSecButton
  case pidIssuanceCanEntryPrimButton
  case pidInspectionPidIssuerTitle
  case pidIssuanceWalletPinSetupPrimButton // Next
  case pidIssuanceWalletPinReenterPrimButton // Set
  case pidIssuanceDataConsentIssuerTitle
  case pidPresentationWalletPinEntryPrimButton
  case eidSetupCardPinReenterPrimButton
  case cardPinSetSuccesfully
  case pidIssuanceWalletPinReenterSucces
  case pidIssuanceDataConsentLabelAgeEqualOrOverYes
  case pidIssuanceDataConsentLabelAgeEqualOrOverNo
  case pidInspectionInitialDashboardTempLabel1
  case pidInspectionInitialDashboardTempLabel2

  // MARK: Eid Attributes:
  case eIDAttributeBirthDate
  case eIDAttributeBirthName
  case eIDAttributeFirstNames
  case eIDAttributeNationality
  case eIDAttributeResidentCity
  case eIDAttributeResidentPostal
  case eIDAttributeResidentStreet
  case eIDAttributeName
  case eIDAttributeArtistName
  case eIDAttributePlaceOfBirth
  case eIDAttributeTitle
  case eIDAttributeAddress
  case eIDAttributeAgeInYears
  case eIDAttributeAgeBirthYear
  case eIDAttributeAgeEqualOrOver
  case eIDAttributeAgeEqualOrOverYes
  case eIDAttributeAgeEqualOrOverNo
  case eIDAttributeIssuingCountry
  case eIDAttributeIssuingAuthority
  case eIDAttributeCreatedAt
  case eIDAttributeExpireDate
  case eIDAttributeDocumentType
  case eIDAttributeCommunityId
  case eIDAttributeAuxiliaryConditions
  case eIDAttributeResidentCountry
  
  // MARK: - Backend Error cases
  case walletRegistrationServiceUnavailableTitle
  case walletRegistrationServiceUnavailableParagraph
  case walletRegistrationServiceUnavailablePrimaryButtonTitle
  case walletRegistrationBadRequestTitle
  case walletRegistrationBadRequestParagraph
  case walletRegistrationBadRequestPrimaryButtonTitle
  case walletRegistrationInternalErrorTitle
  case walletRegistrationInternalErrorParagraph
  case walletRegistrationInternalErrorPrimaryButtonTitle
  case walletRegistrationIntegrityVerificationFailedTitle
  case walletRegistrationIntegrityVerificationFailedParagraph
  case rwscdRegistrationServiceUnavailableTitle
  case rwscdRegistrationServiceUnavailableParagraph
  case rwscdRegistrationServiceUnavailablePrimaryButtonTitle

  case rwscdRegistrationBadRequestTitle
  case rwscdRegistrationBadRequestParagraph
  case rwscdRegistrationBadRequestPrimaryButtonTitle
  case rwscdRegistrationInternalErrorTitle
  case rwscdRegistrationInternalErrorParagraph
  case rwscdRegistrationInternalErrorPrimaryButtonTitle
  case walletAttestationAccountUnknownTitle
  case walletAttestationAccountUnknownParagraph
  case walletAttestationAccountUnknownPrimaryButtonTitle
  case walletAttestationAuthVerificationFailedTitle
  case walletAttestationAuthVerificationFailedParagraph
  case walletAttestationAuthVerificationFailedPrimaryButtonTitle
  
  case globalErrorTitle
  case globalErrorParagraph
  case globalErrorPrimaryButtonTitle
  case globalErrorWalletRevoked
  case globalErrorWalletRevokedBody
  case globalErrorWalletRevokedPrimButton
  
  case pidPresentationRetryCounterResetOverlayTitle
  case pidPresentationRetryCounterResetOverlayParagraph
  case pidPresentationRetryCounterResetOverlayButton

  case globalMenu
  case globalNext
  case globalMenuItemSettings
  case globalRetrieveLogs
  case transactionCodeViewTitle
  case transactionCodeViewDescription
  case logsDownloadDisclaimer

  case eaaOfferViewTitle
  case eaaOfferViewSubTitle
  case eaaOfferViewTxCodeInfo([String])
  case eaaOfferViewPrimaryButtonTitle
  case eaaOfferViewLoadingText
  case eaaOfferViewTxCodeFlowInstruction

  case eaaOfferTransactionCodeViewTitle([String])
  case eaaOfferTxCodeInvalidEntry

  case eaaConsentViewTitle
  case eaaConsentViewSubTitle
  case eaaConsentPrimaryButtonTitle
  case eaaConsentCancelPopupTitle
  case eaaConsentCancelPopupSubTitle
  case eaaIssuanceDialogCancelTitle
  case eaaIssuanceDialogCancelSubTitle
  case eaaIssuanceDialogCancelPrimButton
  case eaaIssuanceDialogCancelSecButton
  case eaaIssuanceTransactionCodeEntryPrimButton
  case eaaIssuanceLoadingTitle
  case eaaIssuanceSuccessTitle
  case eaaIssuanceFailureTitle
  case eaaIssuanceFailureSubTitle
  case buttonViewData

  case pidPresentationRetryCounterRouteToOverview

  // MARK: Accessibility keys
  /// Spoken names for icon-only controls, which carry no title of their own. Copy comes from the Figma export.
  case globalBackButtonA11y
  case globalCloseButtonA11y
  case globalShowDigitsButtonA11y
  case globalHideDigitsButtonA11y

  /// Not yet covered by the Figma export, so the copy lives only in the catalog.
  case headerAccessibilityHelp
  /// Progress read as one value, taking the current step and the total.
  case headerAccessibilityProgress([String])
  case pinAccessibilityFieldLabel
  /// Entry progress for screen readers. Takes the digits entered and the total, never the digits themselves.
  case pinAccessibilityDigitsEntered([String])
  /// As `pinAccessibilityDigitsEntered`, for fields that accept more than digits.
  case pinAccessibilityCharactersEntered([String])
  
  // MARK: Revocation keys
  case appOnboardingWalletRevocationIntroTitle
  case appOnboardingWalletRevocationIntroPara1
  case appOnboardingWalletRevocationIntroPara2
  case appOnboardingWalletRevocationIntroPrimButton
  case appOnboardingWalletRevocationSaveKeyTitle
  case appOnboardingWalletRevocationSaveKeyHeadline1
  case appOnboardingWalletRevocationSaveKeyCopyButton
  case appOnboardingWalletRevocationSaveKeyCopiedButton
  case appOnboardingWalletRevocationSaveKeyShareButton
  case appOnboardingWalletRevocationSaveKeyCheckboxLabel
  case appOnboardingWalletRevocationSaveKeyPrimButton

  case eaaIssuerInfoTitle
}

public extension LocalizableStringKey {
  var toString: String {
    LocalizableManager.shared.get(with: self)
  }
  var toLocalizedStringKey: LocalizedStringKey {
    LocalizedStringKey(self.toString)
  }
}
